import {
    AlignCenter,
    AlignJustify,
    AlignLeft,
    AlignRight,
    Bold,
    Code,
    CodeSquare,
    Highlighter,
    Image,
    Italic,
    Link,
    List,
    ListOrdered,
    ListTodo,
    Quote,
    Redo,
    RemoveFormatting,
    SeparatorHorizontal,
    Strikethrough,
    Subscript,
    Superscript,
    Table,
    Underline,
    Undo,
    Video,
} from "lucide-react";

export const HIGHLIGHT_COLORS = [
    { label: "Amarillo", value: "#fef08a" },
    { label: "Verde", value: "#86efac" },
    { label: "Azul", value: "#93c5fd" },
    { label: "Rosa", value: "#f9a8d4" },
    { label: "Naranja", value: "#fdba74" },
    { label: "Morado", value: "#d8b4fe" },
    { label: "Cyan", value: "#67e8f9" },
    { label: "Rojo", value: "#fca5a5" },
    { label: "Limpiar", value: "" },
] as const;

export const TEXT_COLORS = [
    { label: "Default", value: "" },
    { label: "Rojo", value: "#ef4444" },
    { label: "Azul", value: "#3b82f6" },
    { label: "Verde", value: "#22c55e" },
    { label: "Naranja", value: "#f97316" },
    { label: "Morado", value: "#a855f7" },
    { label: "Rosa", value: "#ec4899" },
    { label: "Cyan", value: "#06b6d4" },
    { label: "Gris", value: "#6b7280" },
] as const;

export const ICONS = {
    Bold,
    Italic,
    Strike: Strikethrough,
    Underline,
    Code,
    Link,
    AlignLeft,
    AlignCenter,
    AlignRight,
    AlignJustify,
    BulletList: List,
    OrderedList: ListOrdered,
    TaskList: ListTodo,
    Table,
    Image,
    Video,
    Quote,
    CodeBlock: CodeSquare,
    HRule: SeparatorHorizontal,
    Undo,
    Redo,
    ClearFormat: RemoveFormatting,
    Highlight: Highlighter,
    Superscript,
    Subscript,
} as const;
